config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'posts#index'
  resources :posts do
    resources :comments
    resources :likes
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :post_category
  belongs_to :creator, class_name: 'User'

  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, class_name: 'PostLike', dependent: :destroy
end

app/models/post/comment.rb
# frozen_string_literal: true

class Post
  class Comment < ApplicationRecord
    has_ancestry

    belongs_to :post
    belongs_to :user
  end
end

app/models/post/like.rb
# frozen_string_literal: true

class Post
  class Like < ApplicationRecord
    belongs_to :user
    belongs_to :post
  end
end

app/models/post_category.rb
# frozen_string_literal: true

class PostCategory < ApplicationRecord
  has_many :posts, dependent: :nullify

  validates :name, presence: true
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  has_ancestry

  belongs_to :post
  belongs_to :user
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts, foreign_key: :creator_id, inverse_of: :creator, dependent: :nullify
  has_many :post_comments, dependent: :nullify
  has_many :post_likes, dependent: :nullify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :check_user, :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to @post, notice: I18n.t('comment_created')
    else
      redirect_to @post
    end
  end

  private

  def check_user
    return if user_signed_in?

    redirect_to user_session_path
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:post_comment).permit(:content, :parent_id)
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :check_user, :set_post

  def create
    @like = @post.likes.build
    @like.user_id = current_user.id
    @like.save

    redirect_to @post
  end

  def destroy
    @post.likes.delete(params[:id])
    redirect_to @post
  end

  private

  def check_user
    return if user_signed_in?

    redirect_to user_session_path
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/post/comments_controller.rb
# frozen_string_literal: true

class Post
  class CommentsController < ApplicationController
    before_action :set_post

    def create
      @comment = @post.comments.build(comment_params)
      # FIXME: handle cases when user is undefined
      @comment.user_id = current_user.id

      if @comment.save
        redirect_to @post, notice: 'Comment was successfully created.'
      else
        redirect_to @post
      end
    end

    private

    def set_post
      @post = Post.find(params[:post_id])
    end

    def comment_params
      params.require(:post_comment).permit(:content, :parent_id)
    end
  end
end

app/controllers/post/likes_controller.rb
# frozen_string_literal: true

class Post
  class LikesController < ApplicationController
    before_action :set_post

    def create
      likes = @post.likes.where(user_id: current_user.id)

      if likes.count.zero?
        @like = @post.likes.build
        @like.user_id = current_user.id
        @like.save
      else
        likes.each(&:delete)
      end

      redirect_to @post
    end

    private

    def set_post
      @post = Post.find(params[:post_id])
    end

    def comment_params
      params.require(:post_like)
    end
  end
end

app/controllers/post_comments_controller.rb
# frozen_string_literal: true

class PostCommentsController < ApplicationController
  before_action :check_user, :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to @post, notice: I18n.t('comment_created')
    else
      redirect_to @post
    end
  end

  private

  def check_user
    return if user_signed_in?

    redirect_to user_session_path
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:post_comment).permit(:content, :parent_id)
  end
end

app/controllers/post_likes_controller.rb
# frozen_string_literal: true

class PostLikesController < ApplicationController
  before_action :check_user, :set_post

  def create
    @like = @post.likes.build
    @like.user_id = current_user.id
    @like.save

    redirect_to @post
  end

  def destroy
    @post.likes.delete(params[:id])
    redirect_to @post
  end

  private

  def check_user
    return if user_signed_in?

    redirect_to user_session_path
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, :set_like, only: :show

  def index
    @posts = Post.all
  end

  def new
    @post = current_user.posts.build
  end

  def show; end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to root_url, notice: I18n.t('post_created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def set_like
    @like = @post.likes.find_by(user_id: current_user)
  end

  def post_params
    params.require(:post).permit(:title, :body, :post_category_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/layouts/application.html.slim
doctype html
html.h-100
  head
    title Blog
    == csrf_meta_tags
    == csp_meta_tag
    meta name="keywords" content="template language"
    meta name="author" content='author'
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"

    == javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    == stylesheet_pack_tag 'application'

  body.d-flex.flex-column.h-100

    = render 'layouts/shared/nav'

    = render 'layouts/shared/flash'

    main
      .mt-4.mb-5.pb-5
        .container
          h1 = yield :title
          hr

          == yield

    footer.bg-dark.text-light.mt-auto
      .container-xl
        .row.py-2
          = "© maximtop, #{Time.zone.today.year}"

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  .container.my-2
    - flash.each do |_type, msg|
      .alert.alert-info
        = msg

app/views/layouts/shared/_nav.html.slim
.navbar.navbar-expand-lg.navbar-dark.bg-dark
  = link_to root_path, class: 'navbar-brand' do
    = t('general_title')

  .collapse.navbar-collapse
    ul.navbar-nav.ms-auto
      - if user_signed_in?
        li.nav-item
          = link_to new_post_path, class: 'nav-link' do
            =< t('create_post')
        li.nav-item
          = link_to destroy_user_session_path, class: 'nav-link', method: :delete do
            =< t('sign_out')
      - else
        li.nav-item
          = link_to user_session_path, class: 'nav-link' do
            =< t('log_in')
        li.nav-item
          = link_to new_user_registration_path, class: 'nav-link' do
            =< t('sign_up')

app/views/posts/_comments_children.html.slim
- children.each do |children_comment|
  hr.my-2
  div
    span.me-1
      = children_comment.user.email
    span.text-muted
      = children_comment.created_at
    p
      = children_comment.content
    hr
    button.btn.btn-link.text-muted.btn-sm [
      aria-controls="form-wrapper-#{children_comment.id}"
      aria-expanded="false"
      data-bs-target="#form-wrapper-#{children_comment.id}"
      data-bs-toggle="collapse"
      type="button"
    ]
      = t('reply')
    .collapse id="form-wrapper-#{children_comment.id}"
      .card.card-body
        = render 'comments_form', parent_id: children_comment.id
    - if children_comment.has_children?
      .ms-4
        = render 'comments_children', children: children_comment.children

app/views/posts/_comments_form.html.slim
.pt-4
  = simple_form_for @post.comments.build, url: post_comments_path(@post) do |f|
    = f.error_notification
    = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

    - if defined?(parent_id)
      = f.hidden_field :parent_id, value: parent_id
    = f.input :content, label: false

    = f.button :submit, class: 'btn-success mt-4 btn-block'

app/views/posts/_form.html.slim
= simple_form_for(@post) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :title
  = f.input :body
  = f.association :post_category

  = f.button :submit, class: 'btn-success mt-4 btn-block'

app/views/posts/index.html.slim
= content_for :title do
  = t('title')

- @posts.each do |post|
  .card.mb-3
    .card-body
      h5.card-title
        = link_to post do
          = post.title
      .card-text.mb-2
        = post.body
      .small.mt-auto
        span.me-3.text-muted
          = t('liked', count: post.likes.count)
        span.me-3.text-muted
          = time_ago_in_words(post.created_at)
        span.text-muted
          = post.creator.email

app/views/posts/new.html.slim
= content_for :title do
  = t('new_post')

== render 'form'

hr

= link_to t('back'), :back, class: 'btn btn-outline-primary'

app/views/posts/show.html.slim
= content_for :title do
  = @post.title

p
  = @post.body

.d-flex.flex-row.justify-content-between
  div
    span.me-2
      = @post.creator.email
    span
      = time_ago_in_words(@post.created_at)
  div
    span.me-2
      = @post.likes.count
    - if @like
      = link_to post_like_url(post_id: @post.id, id: @like.id) { action :destroy }, method: :delete do
        i.fas.fa-thumbs-up
    - else
      = link_to post_likes_url(post_id: @post.id) { action :create }, method: :post do
        i.far.fa-thumbs-up

legend Comments
== render('comments_form')

.pt-4
  - @post.comments.each do |comment|
    - if comment.user && !comment.has_parent?
      .card
        .card-header
          = comment.user.email
        .card-body
          = comment.content
          - if comment.has_children?
            .small
              = render 'comments_children', children: comment.children
        .card-footer
          button.btn.btn-link aria-controls="form-wrapper-#{comment.id}" aria-expanded="false" data-bs-target="#form-wrapper-#{comment.id}" data-bs-toggle="collapse" type="button"
            = t('reply')
          .collapse id="form-wrapper-#{comment.id}"
            = render 'comments_form', parent_id: comment.id